#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Use the Node version from .nvmrc
nvm use

# Run lint-staged
pnpm lint-staged
